---
title: News
author: ''
date: '2024-06-02'
slug: news
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2024-06-02T23:15:29-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
weight: 98
---

|Date|Updates|
|---|---------|
|06/28 - 07/03, 2026|Pratheepa co-organizes a BIRS Workshop on Emerging Challenges in Statistical Modeling for Transportation Research, The Banff Centre, Canada|
|05/31 - 06/03, 2026|Pratheepa will present (invited session in actuarial science) at the 2026 Statistical Society of Canada Annual Meeting, McMaster University, Canada|
|03/17/2026| Pratheepa will present at the University of Waterloo, Statistics and Biostatistics Seminar|
|10/2025| Pratheepa presented at the Statistics Colloquium, Department of Statistical Sciences, University of Toronto|
|09/2025| Pengfei defended his PhD thesis - congrats Frank!|
|08/2025| Submitted paper - [Sparse Seemingly Unrelated Regression (SSUR) Copula Mixed Models for Multivariate Loss Reserving](https://arxiv.org/abs/2509.05426)
|08/2025| Pratheepa presented at the 14th High Dimensional Data Analysis Workshop, Central Michigan University Biological Station, Beaver Island, USA|
|07/2025| Frank presented at the Actuarial Research Conference, Society of Actuaries, York University, Canada|
|06/2025| Submitted paper - [A Robust Nonparametric Framework for Detecting Repeated Spatial Patterns](https://arxiv.org/abs/2506.14103)|
|06/2025| Submitted paper - [Scalable Spatiotemporal Modeling for Bicycle Count Prediction](https://arxiv.org/abs/2506.07582)|
|06/2025|Rajitha presented at the International Conference on Statistics and Data Science, Vancouver, BC, Canada|
|05/2025| Pratheepa presented at the Statistical Society of Canada, Annual Meeting, University of Saskatchewan, Canada|
|05/2025| Pratheepa presented at the Department Colloquium, Department of Statistical and Actuarial Sciences, Western University|
|01/2025| Pratheepa presented at the Scientific Seminar, Department of Decision Science, HEC Montreal|
|12/2024| Rajitha defended his Master's thesis - congrats Rajitha!|
|06/2024|Ishanka Fernando presented at the [SSC 2024 Annual Meeting](https://ssc.ca/en/meeting/annual/presentation/time-aligned-latent-dirichlet-allocation-longitudinal-microbiome-data)|
|05/2024|Pratheepa presented at the [CANSSI Ontario Research Day](https://canssiontario.utoronto.ca/event/research-day-2024/)|
|04/2024|Xinyue Cui and Kevin Chen presented their senior research projects - congrats Xinyue and Kevin!|
|03/2024|Pratheepa presented at Dalhousie University, Department of Mathematics and Statistics, Seminar|
|02/2024|Pratheepa presented at the University of Guelph, Department of Mathematics and Statistics, Seminar|
|01/2024|Ishanka Fernando defended her Master's thesis - congrats Ishanka!|
