---
title: STATS 3DS3 (Winter 2021, McMaster)
author: ''
date: '2021-09-05'
slug: stats3ds3
categories: []
tags: []
subtitle: ''
summary: 'Intoduction to Data Science Theory.'
authors: []
lastmod: '2021-09-05T23:48:43-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
weight: 98
---

# Description

[Course link.](https://academiccalendars.romcmaster.ca/preview_course_nopop.php?catoid=41&coid=217177)

# Syllabus

## Course overview

An introduction to data science theory is provided with some focus on analytics. Topics covered include an introduction to [\blc R\bc](http://cran.r-project.org) and other appropriate computational platforms, data types, data manipulation, data frames, data visualization, data reporting, statistical/machine learning, classification, clustering, cross-validation, classification and regression trees, gradient boosting, ridge regression, LASSO, and generalized additive models. Familiarity with some computer package, e.g., SAS, Python, or MatLab, is required. This course includes a scientific communication component. 


## Expected outcomes

Upon completion of this course, the student will be able to: 

* use visualization tools to explore the data using R
* perform analysis using unsupervised and supervised learning methods 
* analyze a real data set of moderate size using R and interpret the output 
* write reusable data analysis reports using [\blc R\bc](http://cran.r-project.org), [\blc RStudio\bc](https://rstudio.com/), and [\blc RMarkdown \bc](https://rmarkdown.rstudio.com/)

##  Course Information

- Time: 
  - C01: WF 3:30 PM - 4:20 PM
  - L01: Tu 1:30 PM - 2:20 PM or L02: M 12:30 PM - 1:30 PM
- Location: Virtual classroom discussion in Zoom (C01) and Virtual tutorial discussion in Zoom (L01 or L02)
- Sessional dates: January 11, 2021 - April 14, 2021 

## Prerequisites

One of [\blc ECON 3EE3\bc](https://academiccalendars.romcmaster.ca/preview_course_nopop.php?catoid=38&coid=204480) or [\blc PNB 3XE3\bc](https://academiccalendars.romcmaster.ca/preview_course_nopop.php?catoid=38&coid=203323) or [\blc SFWRTECH 4DA3 \bc](https://academiccalendars.romcmaster.ca/preview_course_nopop.php?catoid=38&coid=204426) or [\blc STATS 3A03\bc](https://academiccalendars.romcmaster.ca/preview_course_nopop.php?catoid=38&coid=203709).


## Textbook

- Suggested textbooks:
  - **ISLR**: [\blc _An Introduction to Statistical Learning with Applications in R_\bc](https://campusstore.mcmaster.ca/cgi-mcm/ws/txsub.pl?wsTERMG1=211&wsDEPTG1=STATS&wsCOURSEG1=3DS3&wsSECTIONG1=DAY%20C01&crit_cnt=1) by Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani (Springer, 1st ed., 2013). - available at campus store.
  - **RDS**: [\blc _R for Data Science_\bc](https://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham. - available online.
  - **RMC**: [\blc _R Markdown Cookbook_\bc](https://bookdown.org/yihui/rmarkdown-cookbook/) by Yihui Xie, Christophe Dervieux, Emily Riederer. - available online.

## Software
This course uses R and RStudio, which are both free. We recommend to set-up the computing environment earlier. We will also use the first-week lab session to ensure everyone is up and running with the computing environment. 

- Install the following software (follow the interactive tutorial to install R and R Studio: [\blc click here\bc](https://learnr-examples.shinyapps.io/ex-setup-r/#section-install-r)):
  - R (required): [\blc https://www.r-project.org/\bc](https://www.r-project.org/).
  - RStudio is highly recommended for syntax highlighting, package management, document generation, and more: [\blc https://www.rstudio.com/\bc](https://www.rstudio.com/).
      - The newest version of RStudio is highly recommended.
  - Latex, which will enable you to create PDFs directly from the RMarkdown in RStudio.
      - Install [\blc TinyTex\bc](https://yihui.name/tinytex/) package: `install.packages("tinytex", repos =  "https://cloud.r-project.org/")`.
      - After installing [\blc TinyTex\bc](https://yihui.name/tinytex/), close RStudio.
      - Reopen RStudio.
      - Run the following: `tinytex::install_tinytex()`.
      
      
##  Evaluation

The homework assignments and bonus points will determine the final letter grade for this course:

- Six homework assignments will be assigned.
- The best five assignments will count towards your overall grade.
- Each of your five best assignments will be worth 20% of the final grade.

The final percentage to letter grade conversion will follow McMaster’s Grading Scale.

# Lecture notes

## Course Schedule

|Date|Week|Topic|Readings|Notes|
|--|--|--|--|--|
|**01/11/2021** or **01/12/2021**|**Week 1 (Lab 1)**|Set up R, R Studio, RMarkdown example|1) [\blc Interactive tutorial to install R and R Studio\bc](https://learnr-examples.shinyapps.io/ex-setup-r/#section-install-r)  2) RMarkdown for Scientists [\blc Chapter 1-5\bc](https://rmd4sci.njtierney.com/)||
|**01/13/2021**|Week 1 (Lecture 1)|Course introduction|1) **RDS** [\blc Chapter 1-2\bc](https://r4ds.had.co.nz/introduction.html) 2) [\blc Outline\bc](https://macdrive.mcmaster.ca/f/37b7eb04845b44208711/) 3) RMarkdown for Scientists [\blc Chapters 6-13\bc](https://rmd4sci.njtierney.com/) 4) **RDS** [\blc Chapter 4\bc](https://r4ds.had.co.nz/workflow-basics.html) ||
|**01/15/2021**|Week 1 (Lecture 2)|Data visualization I|1) **RDS** [\blc Chapter 3\bc](https://r4ds.had.co.nz/data-visualisation.html)  2) **RDS** [\blc Chapter 7.1-7.2\bc](https://r4ds.had.co.nz/exploratory-data-analysis.html)  3) **Modern Statistics for Modern Biology** [\blc Chapter 3\bc](http://web.stanford.edu/class/bios221/book/Chap-Graphics.html) ||
|**01/18/2021** or **01/19/2021**|**Week 2 (Lab 2)**|Week 1 computing in R|1) Homework assignment template and submission, 2) R tips - **RDS** [\blc Chapter 4\bc](https://r4ds.had.co.nz/workflow-basics.html), 3) RStudio diagnostics - **RDS** [\blc Chapter 6\bc](https://r4ds.had.co.nz/workflow-scripts.html), 4) data visualization -  **RDS** [\blc Chapter 7.1-7.2\bc](https://r4ds.had.co.nz/exploratory-data-analysis.html#exploratory-data-analysis)||
|**01/20/2021**|Week 2 (Lecture 3)|Data visualization II|1) **RDS** [\blc Chapter 5\bc](https://r4ds.had.co.nz/transform.html), 2) **RDS** [\blc Chapter 7.3-7.8\bc](https://r4ds.had.co.nz/exploratory-data-analysis.html#variation)|**Homework 1 posted**|
|**01/22/2021**|Week 2 (Lecture 4)|Data visualization III|1) **RDS** [\blc Chapter 7.3-7.8\bc](https://r4ds.had.co.nz/exploratory-data-analysis.html#variation), 2) Word clouds - **Text Mining With R** [\blc 7 Case study: comparing Twitter archives\bc](https://www.tidytextmining.com/twitter.html), 3) Network - **Modern Statistics for Modern Biology** [\blc Chapter 10\bc](http://web.stanford.edu/class/bios221/book/Chap-Graphs.html), 4) Time series plots - [\blc https://www.r-graph-gallery.com/279-plotting-time-series-with-ggplot2.html\bc](https://www.r-graph-gallery.com/279-plotting-time-series-with-ggplot2.html)||
|**01/25/2021** or **01/26/2021**|**Week 3 (Lab 3)**|Week 2 computing in R|1) **RDS** [\blc Chapter 8\bc](https://r4ds.had.co.nz/workflow-projects.html) (create an RProject for STATS3DS3), 2) R commands for Lecture 3, 3) R commands for Lecture 4, 4) Word clouds - **Text Mining With R** [\blc 7 Case study: comparing Twitter archives\bc](https://www.tidytextmining.com/twitter.html), 5) Network - **Modern Statistics for Modern Biology** [\blc Chapter 10\bc](http://web.stanford.edu/class/bios221/book/Chap-Graphs.html), 6) Time series plots - [\blc https://www.r-graph-gallery.com/279-plotting-time-series-with-ggplot2.html\bc](https://www.r-graph-gallery.com/279-plotting-time-series-with-ggplot2.html)||
|**01/27/2021**|Week 3 (Lecture 5)|Interactive visualization|[\blc Watch the video\bc](https://shiny.rstudio.com/tutorial/)||
|**01/29/2021**|Week 3 (Lecture 6)|Classification| **ISLR** Pages 39 - 42 (K-Nearest Neighbors) |**Homework 1 Due**|
|**02/01/2021** or **02/02/2021**|**Week 4 (Lab 4)**|Week 3 computing in R| 1) RMarkdown - **RDS** [\blc Chapter 26-27.4.2\bc](https://r4ds.had.co.nz/communicate-intro.html), 2) Shiny (Lecture 5), 3) KNN Classifier (Lecture 6)|**Homework 2 posted**|
|**02/03/2021**|Week 4 (Lecture 7)|Classification tree|**ISLR** Chapter 8.1, 8.1.2, 8.1.4|
|**02/05/2021**|Week 4 (Lecture 8)|Regression tree|**ISLR** Chapter 8.1.1, 8.1.4||
|**02/08/2021** or **02/09/2021**|**Week 5 (Lab 5)**|Week 4 computing in R|1) Text mining (word cloud) - [\blc Lab 3\bc](https://pratheepaj.shinyapps.io/Lab3_interactive/), 2) Classification trees - [\blc Breast Cancer Wisconsin (Diagnostic) Data Set from UCI Machine Learning Repository\bc](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29), 3) Strings in R [\blc **RDS** Chapter 14: Strings\bc](https://r4ds.had.co.nz/strings.html)||
|**02/10/2021**|Week 5 (Lecture 9)| Cross-validation |**ISLR** Chapter 5.1|
|**02/12/2021**|Week 5 (Lecture 10)| Bagging |**ISLR** Chapter 8.2.1 |**Homework 3 posted**, **Homework 2 Due**|
|**02/15/2021** or **02/16/2021**|**Week 6 (No lab)**|Midterm recess|||
|**02/17/2021**|Week 6 (Lecture 11)|Midterm recess     ||
|**02/19/2021**|Week 6 (Lecture 12)|Midterm recess     |||
|**02/22/2021** or **02/23/2021**|**Week 7 (Lab 6)**|Week 5 computing in R|1) **ISLR** Lab 8.3.2 (regression tree), 2) **ISLR** Lab 8.3.3 (bagging)||
|**02/24/2021**|Week 7 (Lecture 13)|Random forest and boosting|1) **ISLR** Chapter 8.2.2 and 8.2.3 |
|**02/26/2021**|Week 7 (Lecture 14)|Neural network    |_The Elements of Statistical Learning_ Chapter 11.1-11.4|**Homework 4 posted**, **Homework 3 Due**|
|**03/01/2021** or **03/02/2021**|**Week 8 (Lab 7)**|Week 7 computing in R|1) **ISLR** Lab 8.3.3 and 8.3.4 (RF and boosting) 2) classification using NN||
|**03/03/2021**|Week 8 (Lecture 15)|Clustering I    |1) **ISLR** Chapter 10.3.1|
|**03/05/2021**|Week 8 (Lecture 16)|Clustering II   |2) **ISLR** Chapter 10.3.1||
|**03/08/2021** or **03/09/2021**|**Week 9 (Lab 8)**|Week 8 computing in R|||
|**03/10/2021**|Week 9 (Lecture 17)|PCA      |**ISLR** Chapter 10.2|
|**03/12/2021**|Week 9 (Lecture 18)|Discriminant analysis I  |**ISLR** Chapter 4.4.1 and 4.4.2|**Homework 5 posted**, **Homework 4 Due**|
|**03/15/2021** or **03/16/2021**|**Week 10 (Lab 9)**|Week 9 computing in R|||
|**03/17/2021**|Week 10 (Lecture 19)|Discriminant analysis II |**ISLR** Chapter 4.4.3 and 4.4.4|
|**03/19/2021**|Week 10 (Lecture 20)|Subset selection |**ISLR** Chapter 6.1||
|**03/22/2021** or **03/23/2021**|**Week 11 (Lab 10)**|Week 10 computing in R|||
|**03/24/2021**|Week 11 (Lecture 21)|Penalized regression I          |1) **ISLR** Chapter 2.2, **ISLR** Chapter 6.2.1|
|**03/26/2021**|Week 11 (Lecture 22)|Penalized regression II       |**ISLR** Chapter 6.2.2 and 6.2.3|**Homework 6 posted**, **Homework 5 Due**|
|**03/29/2021** or **03/30/2021**|**Week 12 (Lab 11)**|Week 11 computing in R|||
|**03/31/2021**|Week 12 (Lecture 23)|Logistic regression I    |**ISLR** Chapter 4.3.1|
|04/02/2021||||\rc Good Friday: No classes or examinations\bc|
|**04/05/2021** or **04/06/2021**|**Week 13 (Lab 12)**|Week 12 computing in R|||
|**04/07/2021**|Week 13 (Lecture 24)|Logistic regression II    |**ISLR** Chapter 4.3.2 and 4.3.3|
|**04/09/2021**|Week 13 (Lecture 25)|Sensitivity and specificity||**Homework 6 Due**|
|**04/12/2021** or **04/13/2021**|**Week 14 (Lab 13)**|Week 13 computing in R|||
|**04/14/2021**|Week 14 (Lecture 26)|Wrap-up||

## Important dates

|Date|Day|Description|
|--|--|--|
|January 11, 2021| Monday |Classes begin|
|January 19, 2021| Thuesday |Last day for enrollment and course changes (drop/add)|
|February 15 to February 19, 2021 |Monday- Friday| Mid-term recess|
|March 19, 2021|Friday | Last day for withdrawing from courses without failure by default|
|April 2, 2021 | Friday | Good Friday: No classes or examinations |
|April 8 to April 14, 2021|Thursday - Wednesday| Test and Examination Restriction |
|April 14, 2021|Wednesday| Classes End|    
|April 15 to April 30, 2021 |Thursday - Friday| Final Examinations|

## R Markdown files

Available upon request.