---
title: Team Members
author: ''
date: '2021-09-05'
slug: current-hqp
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-09-05T11:53:06-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
weight: 99
---

# Postdocs

|Name|Role|Project|
|---|----|-----|
|To be recruited in 2026/2027||Generative models for repeated spatial patterns|

# PhD Students

|Name|Role|Project|
|---|----|-----|
|To be recruited for 2026/2027||Generative models for repeated spatial patterns/transfer function methods for dynamic factor models/estimating equations-based inference|

# Master's Students

|Name|Role|Project|
|---|----|-----|
|Simranjeet Bilkhu (09/2024-02/2026)|M.Sc. in Statistics|Dynamic factor models|
|Gus Vietze (09/2025 - 12/2026)|M.Sc. in Statistics|Transportation problems|
|Kaiming Zhang (09/2025 - 12/2026)|M.Sc. in Statistics (co-supervision with Dr. Anas Abdallah)|Loss reserving and risk captial analysis|
|Amanpreet Singh (09/2025 - 08/2027)|M.Sc. in Computational Science and Engineering|Computational methods for spatial repeated patterns|

# Undergraduate students

|Name|Role|Project|
|---|----|-----|
|To be recruited for 2026/2027||Project to be discussed|





